<div class="creditos">
            <p>..::Créditos do site::..</p>
</div>
            
<div id="footer">
                <p>Giovani Castilho - Gabriel Paggio - Otavio Vilella</p>
                <a href="http://www.facebook.com/Maizeena" target="_blank"><img src="facebook.png" width="25" height="25" alt="Facebook"></a>&nbsp;<a href="http://www.twitter.com/wgbdvs_" target="_blank"><img src="twitter.png" width="25" height="25" alt="Twitter"></a>&nbsp;<a href="http://www.instagram.com/himynamesgio_" target="_blank"><img src="instagram.png" width="25" height="25" alt="Instagram"></a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.facebook.com/gabriel.delpaggio" target="_blank"><img src="facebook.png" width="25" height="25" alt="Facebook" target="_blank"></a>&nbsp;<a href="http://www.twitter.com/GabrielPaggio" target="_blank"><img src="twitter.png" width="25" height="25" alt="Twitter"></a>&nbsp;<a href="http://www.instagram.com/gabriel_paggio" target="_blank"><img src="instagram.png" width="25" height="25" alt="Instagram"></a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.facebook.com/otavio.villela" target="_blank"><img src="facebook.png" width="25" height="25" alt="Facebook" target="_blank"></a>&nbsp;<a href="http://www.twitter.com/otaviovillela" target="_blank"><img src="twitter.png" width="25" height="25" alt="Twitter"></a>&nbsp;<a href="http://www.instagram.com/tatavillela" target="_blank"><img src="instagram.png" width="25" height="25" alt="Instagram"></a>
</div>