        <nav id="nav">
            <ul>
                <li><a href="index.php">Login</a></li>
                <li><a href="home.php">Pagina Inicial</a></li>
                <li><a href="sobre.php">Sobre</a></li>
                <li><a href="sb.php">SuperBowl</a></li>
                <li><a href="hall.php">Hall da Fama</a></li>
                <li><a href="videos.php">Videos</a></li>
                <li><a href="times.php">Times</a></li>
                <li><a href="placares.php">Placares</a></li>
                <li><a href="null"></a></li>
            </ul>
        </nav>