        <nav id="nav">
            <ul>
                <li><a href="login.html">Login</a></li>
                <li><a href="index.html">Página Inicial</a></li>
                <li><a href="sobre.html">Sobre</a></li>
                <li><a href="sb.html">SuperBowl</a></li>
                <li><a href="hall.html">Hall da Fama</a></li>
                <li><a href="videos.html">Vídeos</a></li>
                <li><a href="times.html">Times</a></li>
                <li><a href="placares.html">Placares</a></li>
                <li><a href="null"></a></li>
            </ul>
        </nav>